version: '3.9'

services:
  ## --------------------------------------------------
  ## | Web Server and application pm2 (node)
  ## --------------------------------------------------
  core-service:
    container_name: core-service
    build:
      context: ./
      dockerfile: .docker/core/Dockerfile
    ports:
      - "${APP_PORT}:${NODE_PORT}"
    restart: unless-stopped
    networks:
      - core-network
    env_file:
      - .env

# Networks
networks:
  core-network:
    driver: bridge